name: Shirena Gonzalez Photography
favicon: null
layout_spectrum: 0.7054893015883863
typography_spectrum: 0.8344115659128875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3605017380323261
  lightness: 0.8442825232632458
  saturation: 0.2656103759072721
  rhythmicContrast: 0.17590713361278176
purpose: []
